pull_request_rules:
  - name: automatic merge when CI passes
    conditions:
      - status-success="Advent of Code 2018-ASP.NET Core-CI"
      - base=master
    actions:
      merge:
        method: merge