pull_request_rules:
  - name: automatic merge when CI passes
    condition:
      - status-success=continous-integration/azurepipelines/pr
      - base=master
    actions:
      merge:
        method: merge