pull_request_rules:
  - name: automatic merge when CI passes
    conditions:
      - status-success=continuous-integration/azure-pipelines/pr
      - base=master
    actions:
      merge:
        method: merge